# Generated by Django 5.1.5 on 2025-04-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_product_rating_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
