# Generated by Django 5.1.5 on 2025-04-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_product_brand_remove_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to='product/image/'),
            preserve_default=False,
        ),
    ]
