# Generated by Django 5.1.5 on 2025-04-27 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userprofile_order_alter_comment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courier/photos/')),
                ('passport_series', models.CharField(max_length=9, unique=True)),
                ('passport_number', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier Profile',
                'verbose_name_plural': 'Courier Profiles',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.courierprofile'),
        ),
        migrations.CreateModel(
            name='KitchenAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='user_app.kitchen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitchen Admin Profile',
                'verbose_name_plural': 'Kitchen Admin Profiles',
            },
        ),
    ]
