# Generated by Django 5.1.5 on 2025-04-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_courierprofile_order_courier_kitchenadminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprofile',
            name='photo',
            field=models.ImageField(default=1, upload_to='courier/photos/'),
            preserve_default=False,
        ),
    ]
